### ISSUE TITLE
Scan feature

### ISSUE THREAD

**Issue by jonhadi** [OSU-CS361-W17/group21_project2#8]
new feature called scan in the game
back end provided - needs front end
will tie it into the fire command
"fire, scan, or cancel"

**Comment by ksteinfeldt** [comment]
Per Canvas: 
"Sorry for the confusion. And yes, you should complete the scan feature. Although it is not included in the graded requirements for Project Stage 2, it will be used heavily in a Cognitive Walkthrough assignment that will be released at the end of this week."

Mid priority.

**Comment by ksteinfeldt** [comment]
Technically works now but something needs to be done about the alert that appears whenever "place" or "fire" is selected.

addressed in: https://github.com/OSU-CS361-W17/group21_project2/pull/23

**Comment by ksteinfeldt** [comment]
Alert is fixed.
